### ISSUE TITLE
Nothing works after setting lockbit fuse

### ISSUE THREAD

**Issue by samayg** [mraardvark/pyupdi#42]
Pretty much what the title says. pyupdi works well on a new chip, but once I set the lockbit fuse to an invalid value (i.e, lock the chip), all other commands fail. Even a "-e" erase command fails, with the output:

> Device is locked. Performing unlock with chip erase.
> Traceback (most recent call last):
>   File "pyupdi.py", line 98, in _main
>     nvm.enter_progmode()
>   File "/Users/samay/Downloads/pyupdi-master/updi/nvm.py", line 34, in enter_progmode
>     if self.application.enter_progmode():
>   File "/Users/samay/Downloads/pyupdi-master/updi/application.py", line 129, in enter_progmode
>     raise Exception("Failed to enter NVM programming mode")
> Exception: Failed to enter NVM programming mode
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "pyupdi.py", line 178, in <module>
>     _main()
>   File "pyupdi.py", line 101, in _main
>     nvm.unlock_device()
>   File "/Users/samay/Downloads/pyupdi-master/updi/nvm.py", line 54, in unlock_device
>     self.application.unlock()
>   File "/Users/samay/Downloads/pyupdi-master/updi/application.py", line 89, in unlock
>     raise Exception("Failed to chip erase using key")
> Exception: Failed to chip erase using key

Not only do all commands fail with this output, the program doesn't run anymore after the attempt (to erase/program/read fuses/anything). Maybe it is getting erased but partially or something.

MPLAB erases the chip fine, and pyupdi works again on the erased chip. Repeated erases/programs etc work fine while the chip is not locked.

Using Python3 and a CP2012 adapter.

**Comment by samayg** [comment]
Update: this might be an issue with unlock timeout being set too low. Passing a higher timeout value to `wait_for_unlock()` might help (default is 100 - consider changing this to 150?)
