### ISSUE TITLE
AtTiny404 link UPDI not OK Reinitialization required

### ISSUE THREAD

**Issue by dreadlordrider** [mraardvark/pyupdi#66]
I know this issue has been raised for different devices, but I feel in my case I have a different condition.
I am using a Raspberry Pi and a FT232R USB UART adapter. The Tiny does not have the UPDI pin configured as an i/o pin. Yet it keeps giving me the error that it failed to be initialized.
I have tried both the GPIO serial and USB2TTL. I changed the GPIO setup according to the link too. but no success.
My terminal output is 
` python3 pyupdi.py -v -d tiny404 -c /dev/ttyUSB0 -b 115200 -f /home/pi/Desktop/test.hex
INFO:phy Opening /dev/ttyUSB0 at 115200 baud
INFO:phy send : [0x0]
INFO:link STCS to 0x03
INFO:phy send : [0x55, 0xc3, 0x8]
INFO:link STCS to 0x02
INFO:phy send : [0x55, 0xc2, 0x80]
INFO:link LDCS from 0x00
INFO:phy send : [0x55, 0x80]
INFO:phy receive : []
INFO:link UPDI not OK - reinitialisation required
INFO:phy Sending double break
INFO:phy Opening /dev/ttyUSB0 at 115200 baud
INFO:link STCS to 0x03
INFO:phy send : [0x55, 0xc3, 0x8]
INFO:link STCS to 0x02
INFO:phy send : [0x55, 0xc2, 0x80]
INFO:link LDCS from 0x00
INFO:phy send : [0x55, 0x80]
INFO:phy receive : []
INFO:link UPDI not OK - reinitialisation required
Traceback (most recent call last):
  File "pyupdi.py", line 178, in <module>
    _main()
  File "pyupdi.py", line 95, in _main
    device=Device(args.device))
  File "/home/pi/Downloads/pyupdi-master/updi/nvm.py", line 17, in __init__
    self.application = UpdiApplication(comport, baud, device)
  File "/home/pi/Downloads/pyupdi-master/updi/application.py", line 17, in __init__
    self.datalink = UpdiDatalink(comport, baud)
  File "/home/pi/Downloads/pyupdi-master/updi/link.py", line 31, in __init__
    raise Exception("UPDI initialisation failed")
Exception: UPDI initialisation failed
INFO:phy Closing /dev/ttyUSB0`

Any help or suggestions will be greatly appreciated.

**Comment by dreadlordrider** [comment]
python3 pyupdi.py -v -d tiny404 -c /dev/ttyUSB0 -b 115200 -f /home/pi/Desktop/test.hex
INFO:phy Opening /dev/ttyUSB0 at 115200 baud
INFO:phy send : [0x0]
INFO:link STCS to 0x03
INFO:phy send : [0x55, 0xc3, 0x8]
INFO:link STCS to 0x02
INFO:phy send : [0x55, 0xc2, 0x80]
INFO:link LDCS from 0x00
INFO:phy send : [0x55, 0x80]
INFO:phy receive : []
INFO:link UPDI not OK - reinitialisation required
INFO:phy Sending double break
INFO:phy Opening /dev/ttyUSB0 at 115200 baud
INFO:link STCS to 0x03
INFO:phy send : [0x55, 0xc3, 0x8]
INFO:link STCS to 0x02
INFO:phy send : [0x55, 0xc2, 0x80]
INFO:link LDCS from 0x00
INFO:phy send : [0x55, 0x80]
INFO:phy receive : []
INFO:link UPDI not OK - reinitialisation required
Traceback (most recent call last):
  File "pyupdi.py", line 178, in <module>
    _main()
  File "pyupdi.py", line 95, in _main
    device=Device(args.device))
  File "/home/pi/Downloads/pyupdi-master/updi/nvm.py", line 17, in __init__
    self.application = UpdiApplication(comport, baud, device)
  File "/home/pi/Downloads/pyupdi-master/updi/application.py", line 17, in __init__
    self.datalink = UpdiDatalink(comport, baud)
  File "/home/pi/Downloads/pyupdi-master/updi/link.py", line 31, in __init__
    raise Exception("UPDI initialisation failed")
Exception: UPDI initialisation failed
INFO:phy Closing /dev/ttyUSB0

**Comment by mraardvark** [comment]
any chance you have access to a scope to see what's happening on the tx/rx lines? :|

**Comment by dreadlordrider** [comment]
![IMG_20200929_154631](https://user-images.githubusercontent.com/53105760/94614408-bd8fb480-026b-11eb-9453-b82d04f0a1d9.jpg)
It is definitely sending something. I have a video of the attempts but I'm unable to upload it here.

**Comment by dreadlordrider** [comment]
![ezgif-3-f9c310f91b59](https://user-images.githubusercontent.com/53105760/94615078-c5038d80-026c-11eb-821b-7435c8f58518.gif)

**Comment by mraardvark** [comment]
Hmmm - maybe you should install a pullup?

**Comment by dreadlordrider** [comment]
So instead of a 4.7k resistor between Tx and UPDI, should I connect Tx, Rx UPDI together and a 4.7k to 3.3V?

**Comment by dreadlordrider** [comment]
This is across TxRx
![IMG_20200929_162803](https://user-images.githubusercontent.com/53105760/94618452-d058b800-0270-11eb-9d21-a1b967bd8401.jpg)

**Comment by mraardvark** [comment]
Looks like the double-break, which is used to "recover" once an error is suspected - any sign of the LDCS/STCS?

**Comment by mraardvark** [comment]
Yes, this is a typical try-doublebreak-retry dialog.
Are you scoping TX with respect to GND or UPDI with respect to GND?

**Comment by dreadlordrider** [comment]
Here is the scope between TX and GND


![ezgif-3-13149cc1bcb7](https://user-images.githubusercontent.com/53105760/94619507-a3a5a000-0272-11eb-86bd-c1ae66e386b2.gif)

**Comment by mraardvark** [comment]
FYI - you might want to try and adjust the trigger to catch one of those shorter negative-pulses as they contain more edges than you can see there, but:
- it looks to me like the device is not responding, or can't be heard
- try scoping UPDI-GND to see if you see the same or an attempted response?
- are you sure you are hooked up to the UPDI pin and it is enabled (not set to GPIO/RESET)?

**Comment by dreadlordrider** [comment]
I'm 100% sure it is not set to reset/gpio.
I have used it so far with arduino IDE connected a nano flashed with jtag2updi. Right now I uploaded a basic blink program connected to pin 4 which is PA6. 
With Arduino IDE I have no problem uploading code.
I just moved to RPi and am unable to upload the same exact HEX file that I uploaded before.
I will try the UPDI to GND again. Right now I had taken all my connections out and was trying different circuits.

**Comment by mraardvark** [comment]
OK.  Last question before I sign off:
- is that y axis correct on the display?  100mV per division makes this signal less than 400mV??  
Or am I reading it wrong.

**Comment by dreadlordrider** [comment]
You are definitely right. it is 320mV 
I just assumed that was how low the voltages are supposed to be. I have it plugged directly into the Pi. The Pi has a 5V2A power source

**Comment by dreadlordrider** [comment]
It maybe an issue with the probe first thing tomorrow I'll change the probe and test it again.

**Comment by mraardvark** [comment]
No progress? Been able to catch any frames on the UPDI side (not TX pin)?

**Comment by dreadlordrider** [comment]
Nothing from UPDI. Right now I'm at the point of giving up on the PyUPDI and going for the Pi->Nano->Tiny via jtag2updi

**Comment by mraardvark** [comment]
Best do what works for you.
I guess you have tried the PI UART directly on its pins?

**Comment by dreadlordrider** [comment]
Yup, I tried both methods. Serial GPIO and usb2serial.
😭

**Comment by mraardvark** [comment]
can you capture and post the UPDI init sequence - not the double break - it should consist of about 3 short frames starting with a SYNC on each.

**Comment by dreadlordrider** [comment]
So I get 3 negative peaks. then the double break. then sometimes 2 sometimes 3 peaks. Maybe its always 3, I just cant see it some times
I tried changing the trigger, yes I can see multiple 1s and 0s. but cant capture it.
